version: '3'

services:

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  apidesafio:
    image: apidesafio
    build:
      context: .
    ports:
      - 44394:80

